### ISSUE TITLE
原版PDF

### ISSUE THREAD

**Issue by jinsanity07git** [fengxiaohu/Operating-Systems#1]
你好，原版PDF的连接好像失效了，可以麻烦补一个新的连接吗？ 谢谢！

**Comment by fengxiaohu** [comment]
你有邮箱吗，我邮箱发给你吧，之前的链接我也是找的别人的

**Comment by fengxiaohu** [comment]
百度网盘：
链接：https://pan.baidu.com/s/1JCHpGlKXFk4zQzYFkPtt8A 
提取码：ismr

**Comment by jinsanity07git** [comment]
感谢分享！ 但是百度网盘里的这份好像只是6页的solution. 如果方便的话可以发我邮箱 jinsanity07@163.com 
🙏

**Comment by fengxiaohu** [comment]
> 感谢分享！ 但是百度网盘里的这份好像只是6页的solution. 如果方便的话可以发我邮箱 [jinsanity07@163.com](mailto:jinsanity07@163.com)
> 🙏

已经发送了，请查收，同时网盘链接也更新了
链接：https://pan.baidu.com/s/1wrEWrr-Ylo20gZpA4A2EeA 
提取码：1011 
复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by fengxiaohu** [comment]
> 感谢分享！ 但是百度网盘里的这份好像只是6页的solution. 如果方便的话可以发我邮箱 [jinsanity07@163.com](mailto:jinsanity07@163.com)
> 🙏

请star一下项目，谢谢啦。能follow我更好啦
